import React from 'react';
import { Inter } from 'next/font/google';
import Header from './components/Header/page';
import NavBar from './components/NavBar/page';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Header />
        <NavBar />
        {children}
        </body>
        </html>
    );
};

export default RootLayout;
